### ISSUE TITLE
Unable to import Fastify

### ISSUE THREAD

**Issue by robtweed** [codesandbox/nodebox-runtime#10]
I see a max string error occurring if I try to import Fastify:

```
  await emulator.fs.init({
    'package.json': JSON.stringify({
      name: 'my-app',
      dependencies: {
       fastify: "latest"
      }
    }),
    'index.js': `
import Fastify from 'fastify';
...etc
```

Importing Express works OK.  I assume the Fastify module is simply too big for the way Nodebox handles things?

**Comment by DeMoorJasper** [comment]
Can you create a complete reproducible we can run?

**Comment by robtweed** [comment]
For completeness, here's my self-contained demo:

index.html:

```
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Nodebox test</title>
  </head>
  <body>
    <script type="module" src="/js/errordemo.js"></script>
    <iframe id="preview"></iframe>
  </body>
</html>
```

/js/errordemo.js:

```
(async () => {
  const {Nodebox} = await import('https://unpkg.com/@codesandbox/nodebox@0.1.0/build/index.mjs');
  const emulator = new Nodebox({
    iframe: document.getElementById('preview'),
  });
  await emulator.connect();
  await emulator.fs.init({
    'package.json': JSON.stringify({
      name: 'my-app',
      dependencies: {
       fastify: "latest"
      }
    }),
    'index.js': `
import Fastify from 'fastify';
console.log(1111111);
    `
  });

  const shell = emulator.shell.create();
  const {id} = await shell.runCommand('node', ['index.js']);
  //const { url } = await emulator.preview.getByShellId(id);

  console.log(id);

})();

```

The crash occurs on the Fastify import line, so the console.log() after it never shows up.

There's no urgency - I should be doing other work anyway but I have to admit this stuff is way too fascinating! :-)

BTW in case anyone is wondering about the (async () => { ... })(); wrapper around the main module: whilst unnecessary for Chrome and Firefox, Safari needs it in order to run async/await modules.

**Comment by robtweed** [comment]
Yes, Fastify is working a treat for me now - awesome stuff!
