### ISSUE TITLE
Not finding a new module in NPM

### ISSUE THREAD

**Issue by robtweed** [codesandbox/nodebox-runtime#14]
I've created a new module/repository in NPM today (golgi-sbadmin).  NPM reports that it has been successfully published.

However if I try to now specify it as a dependency in my Nodebox package.json file, it errors, telling me that golgi-sbadmin cannot be found.

Is this perhaps because you're using a mirror of NPM and it will take time for it to get there?

**Comment by DeMoorJasper** [comment]
Yes, that's because we're cloning the npm registry from their couchdb endpoint. It can take a couple minutes before it's in sync
