### ISSUE TITLE
Urgent: All Nextjs Sandpack are broken (even in production in Sandpack doc). TypeError: Cannot read properties of undefined (reading 'toUTCString')

### ISSUE THREAD

**Issue by paul-berthelot** [codesandbox/nodebox-runtime#25]
# Bug report
When loading a sandpack react client with nextjs template. It throw this error in the sandpack console:
```TypeError: Cannot read properties of undefined (reading 'toUTCString')```

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

**Comment by danilowoz** [comment]
Hey, thanks for reporting this issue! 
We're currently investigating this problem and we will keep this issue update

**Comment by paul-berthelot** [comment]
Thank you!

**Comment by DeMoorJasper** [comment]
Just rolled back our deployment to an earlier version that worked. Will investigate this further tomorrow, apologies for the inconvenience.

We'll also improve our test suite to prevent this in the future.
