### ISSUE TITLE
v0.1.6 not loading from NPM?

### ISSUE THREAD

**Issue by robtweed** [codesandbox/nodebox-runtime#31]
There seems to be a problem with the latest v0.1.6 build in NPM

I can load 0.1.5 using this:

  const {Nodebox} = await import('https://unpkg.com/@codesandbox/nodebox@0.1.5/build/index.mjs');

but get an error if I change it to 0.1.6

Also NPM's web page for the 0.1.6 version crashes for me

Anyone else seeing a similar issue?  Perhaps it's an NPM problem?

**Comment by DeMoorJasper** [comment]
Works fine for me, maybe some caching issue with npm/cloudflare?

**Comment by robtweed** [comment]
NPM is reporting issues and a lot of people seeing it as down, so I think it's a wider NPM problem.  They're investigating apparently.

**Comment by robtweed** [comment]
NPM issue
