### ISSUE TITLE
Svelte (Vite) template can't preview.

### ISSUE THREAD

**Issue by nekochan0122** [codesandbox/nodebox-runtime#32]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [x] sandpack-react

## Description of the problem

![image](https://user-images.githubusercontent.com/47508893/225989887-caadd143-8ea8-4cd9-84f1-32541301d322.png)

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Browser                 | Edge |
| Operating System        | Win11 |

**Comment by DeMoorJasper** [comment]
Seems like vite is using a new esbuild api that is not covered by the version of esbuild-wasm we've set in the template, fixed it in our test suite, gonna update the sandpack codebase now and than this should be resolved.

Also increased the priority of the issue to automatically fetch the correct esbuild-wasm version based on the esbuild version vite asks for
