### ISSUE TITLE
"Error: Failed to get shell by ID ..." when running npm scripts

### ISSUE THREAD

**Issue by frepps** [codesandbox/nodebox-runtime#33]
Hello!

I get an error when running the example on https://github.com/codesandbox/nodebox-runtime/blob/main/README.md 

`Uncaught (in promise) Error: Failed to get shell by ID "clfv3ugjh0000039ox0avsv01"`

It runs if I change:
`const nextProcess = await shell.runCommand('npm', ['dev']);`
to
`const nextProcess = await shell.runCommand('next', ['dev']);`

I noticed the same issue in other projects also. `npm` scripts fails, while running, for example, `node index.js` works.

[Example sandbox](https://codesandbox.io/p/sandbox/romantic-tess-s7qwdc?file=%2Fmain.js&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A39%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A39%7D%5D)

(Open developer console and wait about 10 seconds for `emulator.preview.getByShellId` to time out)

**Comment by DeMoorJasper** [comment]
We don't emulate npm, we leave it up to higher level users like sandpack to implement that the npm logic for now.
