### ISSUE TITLE
`InvalidStateError` when using WebSockets

### ISSUE THREAD

**Issue by CTNicholas** [codesandbox/nodebox-runtime#9]
# Bug report

## Packages affected

-   [ ] sandpack-client
-   [ ] sandpack-react

## Note

First off—there may not be enough info here, sorry about that! Just posting this in case you can identify the error from the message. If needed, I'll try find more info. The [code in the demo](https://github.com/liveblocks/liveblocks/tree/main/examples/nextjs-live-cursors) isn't really relevant, it's just used to highlight the issue occurring in Sandpack, but not in CodeSandbox.

## Description of the problem

I'm getting the following error message when using [Liveblocks](https://liveblocks.io) in a Next.js project in Sandpack, a service that provides a collaborative toolkit for building apps through websockets.

![chrome_1cDF4OxR0T](https://user-images.githubusercontent.com/33033422/220153616-04a84c85-5925-42c1-94b8-cc6005898965.png)

If you take a look at my Sandbox and then "open in CodeSandbox", you'll find that the problem disappears in CodeSandbox. Perhaps the issue is possibly being caused by a WebSockets polyfill? 

Note that I've generated an API key for this demo, but it will be revoked on _2023/03/06_, so the demo will stop working then.

## What were you doing when the problem occurred?

Trying to use Liveblocks, and the Liveblocks package makes use of WebSockets. The code is copied from an old example and it definitely works in a normal environment.

<details><summary>This is where the error occurs in the uglified runtime</summary>

![go5jVPqIq3](https://user-images.githubusercontent.com/33033422/220157112-5a56bb36-7572-4a99-835d-289d96bd4149.png)

</details>

### What steps can we take to reproduce the problem?

The demo is a real-time cursors demo, so open the sandbox then move your mouse over the window to make the error occur. Then try "open in CodeSandbox" and note that the error does not occur there. Note that if you open the preview in two windows, you will see multiplayer cursors.

### Your Environment

| Software                | Name/Version |
| ----------------------- | ------------ |
| Sandpack-react version | 2.0.1             |
| Browser                 | Chrome             |
| Operating System        |  Windows 10            |

PS: Love the project, thanks for your work on it!

**Comment by DeMoorJasper** [comment]
Hey, just merged a fix for this, we redispatched some websocket events without cloning the events in our websocket wrapper which is invalid.

Just tried the demo to verify that it works, I can see my own cursor on another tab and it gives no errors, so it looks fixed

Thanks for reporting this issue and apologies for the late response

**Comment by CTNicholas** [comment]
> Hey, just merged a fix for this, we redispatched some websocket events without cloning the events in our websocket wrapper which is invalid.
> 
> Just tried the demo to verify that it works, I can see my own cursor on another tab and it gives no errors, so it looks fixed (really nice to see a liveblocks demo with nextjs running entirely in a browser :D )
> 
> Thanks for reporting this issue and apologies for the late response

Amazing, thank you for fixing this! ✨
